### ISSUE TITLE
rank and player id swapped

### ISSUE THREAD

**Issue by berak** [smiley1983/halite-match-manager#2]
https://github.com/smiley1983/halite-match-manager/blob/master/manager.py#L125

halite seems to output it the other way round (player_id rank)

                    rank = int(token[1])
                    player = int(token[0]) - 1

seems to be the correct way

(nice, very useful tool, nonetheless, thanks a lot for this ;)

**Comment by fohristiwhirl** [comment]
Assuming this is correct, it means results were interpreted wrong for everything except 1v1 games, I think.

**Comment by smiley1983** [comment]
The verbose output may be in that order, but in quiet mode the rank is first, then the player:

[Halite command line reference](https://halite.io/advanced_command_line.php)

@berak: By the way, this takes code from your old Ants TCP server (mosty for the SQL interactions) - I wasn't sure what to do about attribution and licensing so I've just put the Apache license on this for now - if you'd like this changed, let me know. Also should I add a Contributor Licensing Agreement or some other sort of attribution?

**Comment by berak** [comment]
wrt license: happy go lucky, whatever you think is appropriate.

(if you want my 2ct: since you spent more than 30 minutes changing that code - it's all yours, and no more mine)

**Comment by fohristiwhirl** [comment]
I've tested and I'm 99% certain berak is correct about the bug, and the docs are wrong.

**Comment by berak** [comment]
@fohristiwhirl also, 1x1 or multi player would never make a difference, imho

**Comment by fohristiwhirl** [comment]
Well 1v1 can only output "1 1 \n 2 2" or "2 1 \n 1 2", either of which will be interpreted correctly regardless of bug.

(There's also a fair chance of correct interpretation in a 3 player game.)

**Comment by fohristiwhirl** [comment]
.\halite.exe -q -d <SECOND_PLACE> <THIRD_PLACE> <WINNER>

Output:

1 2
2 3
3 1

**Comment by smiley1983** [comment]
Yes, you are absolutely right. Fix applied, thanks for alerting me!

**Comment by fohristiwhirl** [comment]
(The chance of correct interpretation in 1v1 and 1v1v1 was probably what enabled the results to have *some* correlation with what you'd expect from your own knowledge of how good the bots are.)

**Comment by smiley1983** [comment]
Yes, the correlation was quite strong in my own testing, I didn't even suspect that anything was amiss!

I'll post in the forum and see what gets updated, the code or the docs, before closing this.

**Comment by berak** [comment]
ah, sorry, you're the one to close it, then.

**Comment by smiley1983** [comment]
On second thought you're right, this can be closed and a new one opened if the output changes. Thanks again for calling this to my attention, it could have been a long time before I noticed!
